### PR TITLE
fixed over flow

### PR DESCRIPTION
**Pull request by Abdul-Moiz-Iqbal**
fixed the oveflow of gradient in the testimonials component

### CODE REVIEW

**Comment by Abdul-Moiz-Iqbal** [comment]
if need help with anything else? Please let me know

**Comment by vlhsmylv** [comment]
> if need help with anything else? Please let me know
> 
> 

Hello again!

Thank you very much! I appreciate your assistance 🤝

**Comment by Abdul-Moiz-Iqbal** [comment]
No problem, I will be there for you If you need help in the future, and sorry again for late response

**Comment by vlhsmylv** [comment]
> No problem, I will be there for you If you need help in the future, and sorry again for late response

No, that’s okay :) Thanks again 🙌

**Pull request merged**
